# Site settings
title: DaMove
email: damove@ise.tu-berlin.de
url: https://damove.ditas.github.io
description: "Fog computing paradigm mantra suggests to move the computation closer to where the data are generated to reduce the data traffic and improve the performance of networked systems.
Actually, a lot of improvements can be obtained  without touching the computation deployment but concentrating on optimizing the data movement on both ways: from the edge to the cloud and vice-versa. Based on the nature of the data, decisions on how, when, and where data must be moved has impact on the quality of the system especially in terms of latency, data security and privacy, reliability. The goal of the workshop is to bring together researchers and practitioners in the area of Fog Computing in order to present and discuss methods and techniques to make data movement efficient in Fog Computing environments. Workshop will encourage submissions of research papers, industry papers, and demo to consider the whole spectrum of solutions that current
researches can provide.
"
keywords: "damove, workshop, fog computing, data movement"
tagline: "1st Workshop on Efficient Data Movement in Fog Computing"
meta_author: Werner Sebastian

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 70ad47 #80B3FF
  primary-rgb: "197, 224, 180" #"128,179,255"
  secondary:  c5e0b4 #FD6E8A
  secondary-dark: 385623 #A2122F

# Footer settings
footer:
  copyright: DITAS Project
  url: ditas-project.eu

active_agenda: false

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

chairs:
  - name: Pierluigi Plebani
    url: test
    location: Politecnico di Milano, Italy
  - name: David Garcia-Perez
    url: test
    location: ATOS SA, Spain

pub:
  - name: Sebastian Werner
    url: test
    location: Technical University of Berlin, Germany

pcs:
  - name: Maya Anderson
    location: IBM Research, Haifa, Israel
  - name: Antonio Brogi
    location: University of Pisa, Italy
  - name: Cinzia Cappiello
    location: Politecnico di Milano, Italy
  - name: Ana Juan Ferrer
    location: ATOS SA, Spain
  - name: Ety Khaitzin
    location: IBM Research, Haifa, Israel
  - name: Giovanni Meroni
    location: Politecnico di Milano, Italy
  - name: Achilleas Marinakis
    location: National Technical University of Athens, Greece
  - name: Vrettos Moulos
    location: National Technical University of Athens, Greece
  - name: Frank Pallas
    location: Technical University of Berlin, Germany
  - name: Omer Rana
    location: University of Cardiff
  - name: Mattia Salnitri
    location: Politecnico di Milano, Italy
  - name: Monica Vitali
    location: Politecnico di Milano, Italy
  - name: Sebastian Werner
    location: Technical University of Berlin, Germany


# Build settings
markdown: kramdown
permalink: pretty
